name: Run Python Tests
on:
  push:
    paths:
      - '**.py'
  pull_request: 
    paths:
      - '**.py'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: |
          cd modules/security_hub/code
          python -m pytest
